#!/usr/bin/env python3
""" Factors numbers from a file """
from sys import argv
from math import sqrt


def open_read_file(file_name):
    """Reads integers from a file and returns them as a list"""
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    return [int(line) for line in lines]


def find_factors(n):
    """Finds and prints all factors of a number"""
    factors = []
    for i in range(1, int(sqrt(n)) + 1):
        if n % i == 0:
            factors.append(i)
            if n // i != i:  # Check for perfect squares and print the other factor if not
                factors.append(n // i)
    print("{}: {}".format(n, factors))  # Print number and all its factors


def factor_list(numbers):
    """Factors each number in a list"""
    for num in numbers:
        find_factors(num)


if len(argv) == 2:
    factor_list(open_read_file(argv[1]))
